Viacheslav chernyshov
backumich/vertexcrm pull request #10
Opened 2017-07-02 20:54 UTC by masteriza

Dima, please check and confirm pull request. (=

2017-07-04 20:39 UTC, backumich requested changes

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/beans/Course.java
> +    @Size(min = 5, max = 256, message = COURSE_NAME_MSG)
decrease min to 2 please

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/AddCourseController.java
> +        LOGGER.debug("First request to " + PAGE_JSP);
And what about second one?)

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/AddCourseController.java
> +                modelAndView.setViewName("redirect:" + ALL_COURSE_PAGE_JSP);
can you please include  redirect to the constant?

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/ViewAllCoursesController.java
> +    private static final String PAGE_JSP = "viewAllCourses";
or use this constant

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/CourseDaoImpl.java
> +            courses = jdbcTemplate.query(query, parameters, new CourseDaoImpl.CoursesRowMapping());
why don't you use lambda here?

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/CourseDaoImpl.java
> +            course.setId(resultSet.getInt("id"));
builder?

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/CourseDaoImpl.java
> +        LOGGER.debug("Get all courses list");
you write that you are going to get a list, but getting a quantity. It makes me sad =(

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/CourseLogicImpl.java
> +            dataNavigator.setDataSize(dataSize);
some strange logic here that also changes incoming parameter. This approach is called "side effect". I do remember time when I was able to kill for that...

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/UserLogicImpl.java
> +            dataNavigator.setCurrentNumberPage(1);
same here

2017-07-04 20:39 UTC, backumich commented on web/src/main/java/ua/com/vertex/utils/Aes.java
> +        StringBuilder r = new StringBuilder();
can you rename it please?

2017-07-04 20:39 UTC, backumich commented on web/src/main/webapp/WEB-INF/views/viewAllCourses.jsp
> +                <a id="1" class="page" style="cursor: pointer;"><<</a>
something strange here

2017-07-04 21:16 UTC, masteriza commented on web/src/main/java/ua/com/vertex/beans/Course.java
> +    @Size(min = 5, max = 256, message = COURSE_NAME_MSG)
+

2017-07-04 21:17 UTC, masteriza commented on web/src/main/java/ua/com/vertex/controllers/AddCourseController.java
> +                modelAndView.setViewName("redirect:" + ALL_COURSE_PAGE_JSP);
done

2017-07-04 21:17 UTC, masteriza commented on web/src/main/java/ua/com/vertex/controllers/AddCourseController.java
> +        LOGGER.debug("First request to " + PAGE_JSP);
done

2017-07-04 21:17 UTC, masteriza commented on web/src/main/java/ua/com/vertex/dao/CourseDaoImpl.java
> +            courses = jdbcTemplate.query(query, parameters, new CourseDaoImpl.CoursesRowMapping());
done

2017-07-04 21:27 UTC, masteriza commented on web/src/main/java/ua/com/vertex/dao/CourseDaoImpl.java
> +            course.setId(resultSet.getInt("id"));
done

2017-07-04 21:37 UTC, masteriza commented on web/src/main/java/ua/com/vertex/dao/CourseDaoImpl.java
> +        LOGGER.debug("Get all courses list");
done. don't worry, be happy (=

2017-07-04 22:00 UTC, masteriza commented on web/src/main/webapp/WEB-INF/views/viewAllCourses.jsp
> +                <a id="1" class="page" style="cursor: pointer;"><<</a>
This is not strange. This is the << link to the first page, and this >> to the last page

2017-07-04 22:07 UTC, masteriza commented on web/src/main/java/ua/com/vertex/utils/Aes.java
> +        StringBuilder r = new StringBuilder();
Sorry, but this is not my implementation. I do not know the exact purpose of this variable ((

2017-07-06 09:17 UTC, backumich commented on web/src/main/java/ua/com/vertex/utils/Aes.java
> +        StringBuilder r = new StringBuilder();
then name it "result"

2017-07-06 09:26 UTC, backumich commented on web/src/main/webapp/WEB-INF/views/viewAllCourses.jsp
> +                <a id="1" class="page" style="cursor: pointer;"><<</a>
ok, but can you please take a look on special chars in html? Is it possible to shield it?

2017-07-06 09:29 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/CourseLogicImpl.java
> +            dataNavigator.setLastPage(quantityPages);
can we discuss it?

2017-07-06 09:55 UTC, masteriza commented on web/src/main/java/ua/com/vertex/logic/CourseLogicImpl.java
> +            dataNavigator.setLastPage(quantityPages);
Oh, sure.

2017-07-09 21:36 UTC, masteriza commented on web/src/main/java/ua/com/vertex/utils/Aes.java
> +        StringBuilder r = new StringBuilder();
Done

2017-07-10 12:34 UTC, backumich commented on web/src/main/java/ua/com/vertex/utils/DataNavigator.java
> +    public static DataNavigator updateDataNavigator(DataNavigator dataNavigator, int dataSize) {
1. static method - solution, but kind of "logic" would be better. 2. Side effect again!!!

2017-07-10 14:05 UTC, masteriza commented on web/src/main/java/ua/com/vertex/utils/DataNavigator.java
> +    public static DataNavigator updateDataNavigator(DataNavigator dataNavigator, int dataSize) {
Fixed.

2017-07-11 15:54 UTC, backumich approved these changes

2017-07-11 15:54 UTC, merged