Viacheslav klymenko
backumich/vertexcrm pull request #8
Opened 2017-05-22 17:51 UTC by ViacheslavKlymenko

It seems all right, but this is only a guess. )

2017-06-09 16:33 UTC, backumich requested changes

2017-06-09 16:33 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/CreateNewPaymentController.java
> +
please delete all empty strings except one

2017-06-09 16:33 UTC, backumich commented on web/src/main/java/ua/com/vertex/beans/Course.java
> +    public Course() {
Isn't it redundant?

2017-06-09 16:33 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/CreateCertificateAndAddToUser.java
> +
format your file please

2017-06-09 16:33 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/CreateCertificateAndAddToUser.java
> +            LOGGER.info(String.format("Call - userLogic.searchUser(%s);", userData) + "The data have not been validated!!!");
Don't you  want to use debug level instead of info?

2017-06-09 16:33 UTC, backumich commented on web/src/main/java/ua/com/vertex/controllers/CreateCertificateAndAddToUser.java
> +        LOGGER.debug(String.format("Request to '/selectUser' with user id = (%s). Redirect to ", userId) + SELECT_USER_JSP);
why do you concatenate?

2017-06-09 16:33 UTC, backumich commented on web/src/main/java/ua/com/vertex/context/RootConfig.java
> +    private static final int PASSWORD_STRENGTH = 10;
Don't you want to read it from property?

2017-06-09 17:10 UTC, ViacheslavKlymenko commented on web/src/main/java/ua/com/vertex/context/RootConfig.java
> +    private static final int PASSWORD_STRENGTH = 10;
That's not mine))

2017-06-09 17:14 UTC, ViacheslavKlymenko commented on web/src/main/java/ua/com/vertex/context/RootConfig.java
> +    private static final int PASSWORD_STRENGTH = 10;
But I'll fix it.

2017-06-23 13:19 UTC, backumich requested changes

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/UserDaoImpl.java
> +            LOGGER.warn(String.format("isRegisteredEmail(%s) return (%s)", userEmail, user));
warn? Use debug please and without if-block =) if we've got null, then we need to know about it!

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/UserDaoImpl.java
> +                "phone =:phone, role_id =2 WHERE email =:email";
what a magical role_id =)

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/UserDaoImpl.java
> +                "VALUES (:email, :password, :first_name, :last_name, :phone, 2)";
why 2? I like 13 more! Change it to dynamically computable value or to 13, it is my lucky number! =)

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/dao/interfaces/AccountingDaoInf.java
> +    List<User> getCourseUsers(int courseId);
right place for this method is UserDao

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/PaymentLogicImpl.java
> +        LOGGER.debug(String.format("Call - accountingDaoInf.updateUserDept((%s), (%s) , (%f)) ;",
why don't you put such logging inside called method? Method starts - logging prints.

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/RegistrationUserLogicImpl.java
> +    @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
SuppressWarnings?

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/RegistrationUserLogicImpl.java
> +                    "Passwords do not match!");
Why don't we write an annotation to verify this?

2017-06-23 13:19 UTC, backumich commented on web/src/main/java/ua/com/vertex/logic/RegistrationUserLogicImpl.java
> +                    "Passwords do not match!");
example - http://dolszewski.com/spring/custom-validation-annotation-in-spring/

2017-06-29 19:42 UTC, backumich approved these changes

2017-06-29 19:42 UTC, merged